<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a target="_blank" href="/zend_demo/public/web/Home/index">Go to web page</a>
            </li>
            <?php
            foreach ($this->listModuleByRole as $tmp) {
                ?>
                <li>
                    <?php
                    echo '<a href="' . $tmp['link'] . '"><i class="fa fa-edit fa-fw"></i> ';
                    echo $tmp['name'];
                    $this->ar = json_decode($tmp['sub_pages']);
                    if (sizeof($this->ar) > 0) {
                        echo '<span class="fa arrow"></span>';
                    }
                    echo '</a>';
                    if (sizeof($this->ar) > 0) {
                        echo '<ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">';
                        for ($i = 0; $i < sizeof($this->ar); $i++) {
                            $sub = $this->ar[$i];
                            echo '<li>';
                            echo' <a href="' . $sub->link . '">' . $sub->name . '</a>';
                            echo '</li>';
                        }
                    }
                    ?>
                </li>
            <?php } ?>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>