<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a target="_blank" href="/zendDemo/public/web/Home/index">Go to web page</a>
            </li>
            <?php
            foreach ($this->listModuleByRole as $tmp) {
                ?>
                <li>
                    <?php echo '<a href="' . $tmp['link'] . '">' ?><i class="fa fa-edit fa-fw"></i> <?php echo $tmp['name']; ?> </a>
                </li>
            <?php } ?>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>