<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Adminisrator login page</title>
        <!-- Bootstrap Core CSS -->
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css') ?>
        <!-- MetisMenu CSS -->
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/plugins/metisMenu/metisMenu.min.css') ?>
        <!-- Custom CSS -->
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/sb-admin-2.css') ?>

        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/plugins/jquery/jquery.min.js') ?>
        <!-- Bootstrap Core JavaScript -->
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/plugins/bootstrap/js/bootstrap.min.js') ?>
        <!-- Metis Menu Plugin JavaScript -->
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/plugins/metisMenu/metisMenu.min.js') ?>
        <!-- Custom Theme JavaScript -->
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/sb-admin-2.js') ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <div class="login-panel panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Please Sign In</h3>
                        </div>
                        <div class="panel-body">
                            <form role="form" <?php echo 'action="' . $this->url(array('controller' => 'Login', 'action' => 'login', 'module' => "administrator")) . '"' ?> method="post">
                                <fieldset>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Username" name="username" type="text" autofocus>
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                        </label>
                                    </div>
                                    <!-- Change this to a button or input when using this as a form -->
                                    <?php echo '<button type="submit" class="btn btn-lg btn-success btn-block">Login</a>' ?>
                                </fieldset>
                            </form>
                            <?php
                            if ($this->loginStatus != null && $this->loginStatus == 'false') {
                                ?>
                                <span style="color: red;text-align: center;">Sai username hoặc password </span>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
