<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-12 right-border">
            <div class="footer-about">
                <h2 class="footer-title">About Us</h2>
                <p>This footers are designed to divide the layout through simple designs. Footers are often underestimated by designers and developers. Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. How to create a simple WordPress theme; How to integrate Bootstrap 3.</p>
            </div>
            <div class="copyright hidden-sm hidden-xs">
                <p>Copyrights &copy; 2015 <a href="http://nextbootstrap.com/" title="">Next Bootstrap</a>. All Right Reserved.</p>
                <p>Developed By : <a href="http://sirseni.com/" title="">Sirseni Technology</a></p>
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="col-md-6 col-sm-6">
                <div class="contact-info">
                    <h2 class="footer-title">Contact Info</h2>
                    <div class="single">
                        <i class="fa fa-map-marker"></i>
                        <p>99 Street Address,<br> 
                            Your City, LKG 778569, Country</p>
                    </div>
                    <div class="single">
                        <i class="fa fa-phone"></i>
                        <p>+977-90123987280</p>
                    </div>

                    <div class="single">
                        <i class="fa fa-envelope"></i>
                        <p>info@example.com</p>
                    </div>

                    <div class="social-icon">
                        <ul class="list-inline">
                            <li><a href="http://sirseni.com/" title=""><i class="fa fa-facebook"></i></a></li>
                            <li><a href="http://sirseni.com/" title=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href="http://sirseni.com/" title=""><i class="fa fa-instagram"></i></a></li>
                            <li><a href="http://sirseni.com/" title=""><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 left-border">
                <div class="navigation">
                    <h2 class="footer-title">Navigation</h2>
                    <ul class="list-unstyled">
                        <li><a href="http://centerend.com/" title="">Home</a></li>
                        <li><a href="http://centerend.com/" title="">About Us</a></li>
                        <li><a href="http://centerend.com/" title="">Services</a></li>
                        <li><a href="http://centerend.com/" title="">Terms & Conditions</a></li>
                        <li><a href="http://centerend.com/" title="">Privacy Policy</a></li>
                        <li><a href="http://centerend.com/" title="">Career</a></li>
                        <li><a href="http://centerend.com/" title="">Sitemap</a></li>
                        <li><a href="http://centerend.com/" title="">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="copyright visible-sm visible-xs">
                <p>Copyrights &copy; 2015 <a href="http://nextbootstrap.com/" title="">Next Bootstrap</a>. All Right Reserved.</p>
                <p>Developed By : <a href="http://centerend.com/" title="">Sirseni Technology</a></p>
            </div>
        </div>
    </div>
</div>