<div id="header">
    <?php echo $this->render('/web/head_top.phtml') ?>
    <div class="l-pageWrapper">    			
        <?php echo $this->render('/web/head_main.phtml') ?>
        <?php echo $this->render('/web/head_menu.phtml') ?>
        <?php echo $this->render('/web/head_sub_menu.phtml') ?> 
    </div>     
    <div class="clearfix">&nbsp</div>
    <?php echo $this->render('/web/content.phtml') ?>
</div>