<div class="head-nav">
    <div class="nav" id="primary_nav_wrap">
        <ul>
            <li class="current-menu-item"><a href="#">Home</a></li>

            <?php

            function viewMenu($arrayMenu) {
                for ($i = 0; $i < sizeof($arrayMenu); $i++) {
                    loopChildMenu($arrayMenu[$i]);
                }
            }

            function loopChildMenu($menu) {
                echo '<li><a href="#">'.$menu->getCurrentMenu().'</a>';
                if (sizeof($menu->getArrayChildMenu()) > 0) {
                    echo '<ul>';
                    for ($i1 = 0; $i1 < sizeof($menu->getArrayChildMenu()); $i1 ++) {
                        loopChildMenu($menu->getArrayChildMenu()[$i1]);
                    }
                    echo '</ul>';
                }
                echo '</li>';
            }
            viewMenu($this->listMenusTop);
            ?>

        </ul>
    </div>
</div>
