<div class="l-sidebar">
    <?php echo $this->render('/home/content_left.phtml') ?>

</div>
<div class="l-main">
    <?php $json = json_decode($this->productDetail->detail, true); ?>
    <div id="detail">     
        <div class="clearfix">
            <div class="detail_top_content">
                <span style="float:left; text-align:center">
                    <a <?php echo 'href="' . $this->productDetail->images . '"' ?> title="Áo Hoodie Nam 1296" class="jqzoom" rel='gal1'>
                        <img alt=""  <?php echo 'src="' . $this->productDetail->images . '"' ?> alt=Áo Hoodie Nam 1296" style="border:1px solid #eee; padding:2px; width: 300px;" />
                    </a>            
                </span>
                <div class="info_product fr">   
                    <h2><?php echo $json['name'] ?></h2>
                    <div class="rate_share clearfix">   	
                        <span class="date_up fl">Đăng ngày <?php echo $this->productDetail->create_date ?> - 798 Lượt xem</span>   	
                        <div class="share fr">					
                            <a onClick="share_facebook();" href="javascript:;" title="Share on Facebook">
                                <img  border="0" alt="Share on Facebook" <?php echo 'src="' . $this->baseUrl() . '/images/facebook.png"' ?> />
                            </a>
                            <a onClick="share_twitter();" href="javascript:;" title="Share on Twitter">
                                <img  border="0" alt="Share on Twitter"   <?php echo 'src="' . $this->baseUrl() . '/images/twitter.html"' ?> />
                            </a>
                            <a onClick="share_google();" href="javascript:;" title="Share on Google">
                                <img  border="0" alt="Share on Google"   <?php echo 'src="' . $this->baseUrl() . '/images/google.png"' ?>/>
                            </a>										
                        </div>
                    </div>       		       		
                    <ul>         
                        <li class="list_detail">Mã sản phẩm: <span class="code"><?php echo $json['ID'] ?></span></li>                  
                        <li class="list_detail">
                            <span>Xuất xứ: <?php echo $json['origin'] ?></span>
                        </li>
                    </ul>
                    <div class="conhang"><span>Còn hàng  Call ngay: 0933 952 395</span></div> 
                    <div class="note_detail">
                        <span>Lưu ý&#x3A; Sản phẩm thật có thể chênh lệch màu sắc khoảng 10&#x25; so với hình ảnh trên deal do sự khác nhau về độ phân giải của từng loại màn hình.</span>
                    </div>
                    <div class="clear">&nbsp;</div>
                    <p style="color: #666666; line-height: 20px; margin: 0 0 10px 0;">
                    <div> + <em><?php echo $json['name']; ?></em></div>
                    <div> + Chất liệu : &nbsp;<?php echo $json['origin']; ?></div>
                    <div> + Màu Sắc : <?php echo $json['color']; ?></div>
                    <div> + Kích thước : <?php echo $json['size']; ?></div>
                    <div class="price_order">     
                        <div class="pro_bo_stock_pra" align="center">
                            <b>CHỌN MUA HÀNG</b>
                        </div>       	
                        <div class="detail_price">
                            <p>
                                <br>
                                <span class=""><?php echo $this->productDetail->price; ?> VND</span>
                            </p>
                        </div>           
                        <form <?php echo 'action="' . $this->url(array('controller' => 'Product', 'action' => 'cart')) . '"' ?> method="POST">
                            <div class="detail_order">
                                <span class="pnum">	                 
                                    S&#7889; l&#432;&#7907;ng: 
                                    <input  type="text" name="pnum" value="1" style="width:50px; height:20px;" id="pnum" />
                                    <input  type="hidden" name="idProduct"  style="width:50px; height:20px;" id="idProduct" <?php echo 'value="' . $json['ID'] . '"' ?>/>
                                </span>
                                <button href="javascript:void(0)" title="" class="pro_order fr" type="submit" style=" margin-right: 5px;">		                	
                                </button>
                            </div>
                        </form>
                    </div>
                    <div style="clear:both"></div>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
            <div class="TabViews" id="TabViews">
                <div class="Tabs">
                    <a href="#"><span>Chi tiết</span></a><a href="#"><span>Bình luận</span></a>	              
                </div>    
                <div class="Pages">    
                    <div class="Page">
                        <div> + <em><?php echo $json['name']; ?></em></div>
                        <div> + Chất liệu : &nbsp;<?php echo $json['origin']; ?></div>
                        <div> + Màu Sắc : <?php echo $json['color']; ?></div>
                        <div> + Kích thước : <?php echo $json['size']; ?></div>
                        <br /> <br /> 

                        <?php
                        $arrayImage = explode(",", $json['image']);
                        foreach ($arrayImage as $img) {
                            echo '<img  alt="" src="' . $img . '" style="width: 720px; height: 720px;" /><br /> <br />';
                        }
                        ?>
                    </div>
                </div>      
                <div class="fb-comments" data-href="http://thoitrangchuyensi.com" data-width="670"></div>
                <div class="Page">
                </div>	
                <div class="Page">
                </div>	    	 		
            </div>
        </div>
    </div>    
    <div class="clear">&nbsp;</div>    
    <div class="clear">&nbsp;</div> 
</div>
