<ul class="menu_left">
    <?php

    function viewMenuLeft($arrayMenu) {
        for ($i = 0; $i < sizeof($arrayMenu); $i++) {
            echo "<li>";
            echo '<a class="cate" title="' . $arrayMenu[$i]->getCurrentMenu() . '" href="' . $arrayMenu[$i]->getCurrentMenu() . '"><h2>' . $arrayMenu[$i]->getCurrentMenu() . '</h2></a>';
            echo "<ul>";
            loopChildMenuLeft($arrayMenu[$i]);
            echo "</ul>";
            echo "</li>";
        }
    }

    function loopChildMenuLeft($menu) {
        if (sizeof($menu->getArrayChildMenu()) > 0) {
            for ($i1 = 0; $i1 < sizeof($menu->getArrayChildMenu()); $i1 ++) {
                echo '<li class="sub">';
                echo '<a class="subcate" title="' . $menu->getArrayChildMenu()[$i1]->getCurrentMenu() . '" href="' . $menu->getArrayChildMenu()[$i1]->getCurrentMenu() . '"><h2>' . $menu->getArrayChildMenu()[$i1]->getCurrentMenu() . '</h2></a>';
                loopChildMenuLeft($menu->getArrayChildMenu()[$i1]);
                echo "</li>";
            }
        }
    }

    viewMenuLeft($this->listMenusLeft);
    ?>
    <!--    <li>
            <a class="cate" title="Thời Trang Nữ" href="thoi-trang-nu-gia-si.html"><h2>Thời Trang Nữ</h2></a>
            <ul>
                <li class="sub">
                    <a class="subcate" title="Áo Khoác Nữ" href="ao-khoac-nu-gia-si.html"><h3>Áo Khoác Nữ</h3></a>
                </li>
                <li class="sub">
                    <a class="subcate" title="Váy Đầm" href="vay-dam-gia-si.html"><h3>Váy Đầm</h3></a>
                </li>
                <li class="sub">
                    <a class="subcate" title="Áo Sơ Mi Nữ" href="ao-so-mi-nu-gia-si.html"><h3>Áo Sơ Mi Nữ</h3></a>
                </li>
                <li class="sub">
                    <a class="subcate" title="Đồ Bộ Nữ" href="do-bo-nu-gia-si.html"><h3>Đồ Bộ Nữ</h3></a>
                </li>
                <li class="sub">
                    <a class="subcate" title="Áo Thun Nữ" href="ao-thun-nu-gia-si.html"><h3>Áo Thun Nữ</h3></a>
                </li>
                <li class="sub">
                    <a class="subcate" title="Quần Nữ + Áo len" href="quan-jean-nu-gia-si.html"><h3>Quần Nữ + Áo len</h3></a>
                </li>
                <li class="sub">
                    <a class="subcate" title="Đồ Lót Nữ" href="do-lot-nu-gia-si.html"><h3>Đồ Lót Nữ</h3></a>
                </li>
            </ul>
        </li>-->
</ul>