<div class="box_module">
    <h3 class="module_title">Thống kê truy cập</h3>
    <div class="module_content">
        <div class="block-stat">
            <ul>
                <li class="online">
                    Đang truy cập: <strong>16</strong>
                </li>
                <li class="guest">
                    Khách viếng thăm: <strong>15</strong>
                </li>
                <li class="bot">
                    Máy chủ tìm kiếm: <strong>1</strong>
                </li>
                <li class="today">
                    Hôm nay: <strong>1349</strong>
                </li>
                <li class="month">
                    Tháng hiện tại: <strong>95710</strong>
                </li>
                <li class="statistics">
                    Tổng lượt truy cập: <strong>4152834</strong>
                </li>
            </ul>
        </div>
    </div>
</div>