<div class="head-nav">
    <div class="nav">
        <ul class="nav fl">
            <li class="home">
                <a title="Trang nhất" href="index.html">&nbsp;</a>
            </li>
            <?php
            if ($this->current == 'Product') {
                ?>
                <li class="current">
                    <a title="Sản phẩm" href="shops.html">Sản phẩm</a>
                </li>
            <?php } else { ?>
                <li >
                    <a title="Sản phẩm" href="shops.html">Sản phẩm</a>
                </li>
            <?php } ?>
            <?php
            if ($this->current == 'Introduction') {
                ?>
                <li class="current">
                    <a title="Sản phẩm" href="shops.html">Giới thiệu</a>
                </li>
            <?php } else { ?>
                <li >
                    <a title="Sản phẩm" href="shops.html">Giới thiệu</a>
                </li>
            <?php } ?>    
            <li >
                <a title="Tin Tức" href="tin-tuc.html">Tin Tức</a>
            </li>
            <li >
                <a title="Hướng Dẫn Thanh Toán" href="huong-dan-thanh-toan.html">Hướng Dẫn Thanh Toán</a>
            </li>
            <li >
                <a title="Thành viên" href="users.html">Thành viên</a>
            </li>
            <li >
                <a title="Hỏi đáp" href="faqs.html">Hỏi đáp</a>
            </li>
            <li >
                <a title="Liên hệ" href="contact.html">Liên hệ</a>
            </li>
            <li >
                <a title="Tuyển dụng" href="tuyen-dung.html">Tuyển dụng</a>
            </li>
        </ul>
    </div>
</div>