<div id="nav-menu"> 
    <!--  for menu -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">This's my page</a>
            </div>
            <ul class="nav navbar-nav pull-right">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Instroduction</a></li>
                <li><a href="#">Product</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>
    </nav>
</div>