   
<div id="submenu_nav">
    <div class="eventhl">	
        <marquee onmouseout="this.start()" onmouseover="this.stop()" scrolldelay="3" scrollamount="4" style="padding-top:5px;" direction="left" behavior="scroll">
            <a style="padding-right: 12px; padding-left: 8px;" title="Bạn đang cần tìm nguồn hàng quần áo thời trang giá sỉ?" href="tin-tuc/ban-dang-can-tim-nguon-hang-quan-ao-thoi-trang-gia-si-202.html">Bạn đang cần tìm nguồn hàng quần áo thời trang giá sỉ? - <span class="small">28/0404/15</span></a>		 	
            <a style="padding-right: 12px; padding-left: 8px;" title="Những mẫu áo thời trang luôn được giới trẻ yêu thích nhất hiện nay." href="tin-tuc/nhung-mau-ao-thoi-trang-luon-duoc-gioi-tre-yeu-thich-nhat-hien-nay-201.html">Những mẫu áo thời trang luôn được giới trẻ yêu thích nhất hiện nay. - <span class="small">24/0404/15</span></a>		 	
            <a style="padding-right: 12px; padding-left: 8px;" title="Bộ sưu tập thời trang mát mẻ bạn nên tranh thủ lựa chọn cho kỳ nghỉ lễ." href="tin-tuc/bo-suu-tap-thoi-trang-mat-me-ban-nen-tranh-thu-lua-chon-cho-ky-nghi-le-200.html">Bộ sưu tập thời trang mát mẻ bạn nên tranh thủ lựa chọn cho kỳ nghỉ lễ. - <span class="small">23/0404/15</span></a>		 	
            <a style="padding-right: 12px; padding-left: 8px;" title="Các mẫu áo khoác nam nữ giá sỉ mới nhất trên thị trường" href="tin-tuc/cac-mau-ao-khoac-nam-nu-gia-si-moi-nhat-tren-thi-truong-199.html">Các mẫu áo khoác nam nữ giá sỉ mới nhất trên thị trường - <span class="small">22/0404/15</span></a>		 	
            <a style="padding-right: 12px; padding-left: 8px;" title="Mẫu mã và xu hướng thời trang mới 2015" href="tin-tuc/mau-ma-va-xu-huong-thoi-trang-moi-2015-198.html">Mẫu mã và xu hướng thời trang mới 2015 - <span class="small">21/0404/15</span></a>		 	
            <a style="padding-right: 12px; padding-left: 8px;" title="Mua quần áo giá sỉ - Nơi cung cấp quần áo thời trang giá sỉ tại Tp.HCM" href="tin-tuc/mua-quan-ao-gia-si-noi-cung-cap-quan-ao-thoi-trang-gia-si-tai-tp-hcm-197.html">Mua quần áo giá sỉ - Nơi cung cấp quần áo thời trang giá sỉ tại Tp.HCM - <span class="small">15/0404/15</span></a>		 	
        </marquee>
    </div>
</div>   				