<div class="head-top">
    <?php echo $this->current; ?>
    <div class="refresh-headtop" style="cursor: pointer;">
        <img  <?php echo 'src="'.$this->baseUrl().'/images/refresh.png"'?> alt="Cam kết chất lượng 100%" />
        <span class="txt-headtop">ĐẢM BẢO CHẤT LƯỢNG</span>
    </div>
    <div class="price-headtop" style="cursor: pointer;">
        <img  <?php echo 'src="'.$this->baseUrl().'/images/refresh.png"'?> alt="Kinh Doanh Kiếm Tiền" />
        <span class="txt-headtop">CÙNG KINH DOANH KIẾM TIỀN</span>
    </div>
    <div class="ship-headtop" style="cursor: pointer;">
        <img  <?php echo 'src="'.$this->baseUrl().'/images/refresh.png"'?> alt="Miễn phí vận chuyển nội thành" />
        <span class="txt-headtop">MIỄN PHÍ VẬN CHUYỂN NỘI THÀNH</span>
    </div>
    <div class="hotline-headtop" style="cursor: pointer;">
        <img  <?php echo 'src="'.$this->baseUrl().'/images/refresh.png"'?> alt="Hotline" />
        <span class="txt-headtop" style="color: rgb(51, 51, 51);"> 08.3810.4752 - 0933.952.395</span>
    </div>
</div>