<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NỮ HOÀNG QUẦN JEAN</title>


<!--    <link href="css/bootstrap.min.css" rel="stylesheet"/>
    <link href="css/font-awesome.css" rel="stylesheet"/>
    <link href="css/style00.css" rel="stylesheet"/>
    <link href="css/setmedia.css" rel="stylesheet"/>
    <link href="css/menu-1.css" rel="stylesheet"/>
    <link href="css/slider_full.css" rel="stylesheet"/> slider_full 
    <link  href="css/component.css" rel="stylesheet"/> search 
    <link  href="css/zoom.css" rel="stylesheet"/> prod_slider zoom 
    <link  href="css/related_product.css" rel="stylesheet"/> slider san pham tham khao 


    <script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/nav-menu3.js"></script>menu


    <script type="text/javascript" src="js/style-img.js"></script>
    <script type="text/javascript" src="js/jssor.core.js"></script>
    <script type="text/javascript" src="js/jssor.slider.js"></script>

    <script type="text/javascript" src="js/jssor.utils.js"></script>
    <script type="text/javascript" src="js/slider_full.js"></script> slider_full 
    <script type="text/javascript" src="js/jqueryZoom.js"></script> prod_slider zoom 
    <script type="text/javascript" src="js/related_product.js"></script> slider san pham tham khao -->



</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<header>


    <div class="bg_header">
        <div class="list_header">
            <div class="container">
                <div class="row_pc">
                    <div class="  visible-xs visible-sm menu_mb">

                        <button class="nav-toggle">
                            <div class="icon-menu">
                                <span class="line line-1"></span>
                                <span class="line line-2"></span>
                                <span class="line line-3"></span>
                            </div>
                        </button>
                        <div class="" style="width: 100%; text-align: center">
                            <img style="max-height: 60px; max-width: 70%" src="img/logo.png" alt="">
                        </div>
                    </div>
                    <div class=" pull-right">
                        <ul class="menu_hd_top">
                            <li class="hidden-xs">
                                <a href="" data-toggle="modal" data-target="#nhankm">Đăng ký khuyến mại</a>
                                <div id="nhankm" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="myModalLabel">
                                                    <a href="" style="color: #aaaaaa; font-size: 14px">Đăng ký nhận khuyến mãi</a>
                                                    <button style="color: red;opacity: 0.9" type="button" class="close pull-right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                                </h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Hãy nhập email vào khung bên dưới để nhận thông tin deal tốt hàng ngày. Chúng tôi cam kết sẽ không spam.
                                                </p>
                                                <div class="clearfix"></div>
                                                <div class="input-group">
                                                    <input name="email" type="text" class="validate[required,custom[email]] form-control" placeholder="Đăng ký email để được nhận thông tin khuyến mãi">
                                                    <span class="input-group-addon" onclick="$('#dangkymail').submit()" style="cursor: pointer">
                                                        <i class="fa fa-location-arrow"></i>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="modal-footer">

                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </li>
                            <li class="hidden-xs">
                                <div class="dropdown">
                                    <p onclick="myFunction()" class="dropbtn">Sản phẩm quan tâm</p>
                                    <div id="myDropdown" class="dropdown-content">
                                        <ul class="list_spqt_top">
                                            <li>
                                                <div class="box_spqt_top">
                                                    <div class="row">
                                                        <div class="col-xs-4">
                                                            <a href="" class="img_spqt_top">
                                                                <img class="w_100" src="img/prod1.png" alt=""/>
                                                            </a>
                                                        </div>
                                                        <div class="col-xs-8">
                                                            <div class="name_spqt_top">
                                                                <a href="">Sản phẩm a</a>
                                                            </div>
                                                            <div class="clearfix"></div>
                                                            <div class="prin_spqt_top">
                                                                800.000 vnđ
                                                            </div>
                                                            <div class="clearfix"></div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                        <div class="col-xs-12">
                                                            <div class=" del_spqt_top pull-right">
                                                                <a href="">Xóa</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="box_spqt_top">
                                                    <div class="row">
                                                        <div class="col-xs-4">
                                                            <a href="" class="img_spqt_top">
                                                                <img class="w_100" src="img/prod1.png" alt=""/>
                                                            </a>
                                                        </div>
                                                        <div class="col-xs-8">
                                                            <div class="name_spqt_top">
                                                                <a href="">Sản phẩm a</a>
                                                            </div>
                                                            <div class="clearfix"></div>
                                                            <div class="prin_spqt_top">
                                                                800.000 vnđ
                                                            </div>
                                                            <div class="clearfix"></div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                        <div class="col-xs-12">
                                                            <div class=" del_spqt_top pull-right">
                                                                <a href="">Xóa</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="box_spqt_top">
                                                    <div class="row">
                                                        <div class="col-xs-4">
                                                            <a href="" class="img_spqt_top">
                                                                <img class="w_100" src="img/prod1.png" alt=""/>
                                                            </a>
                                                        </div>
                                                        <div class="col-xs-8">
                                                            <div class="name_spqt_top">
                                                                <a href="">Sản phẩm a</a>
                                                            </div>
                                                            <div class="clearfix"></div>
                                                            <div class="prin_spqt_top">
                                                                800.000 vnđ
                                                            </div>
                                                            <div class="clearfix"></div>
                                                        </div>
                                                        <div class="clearfix"></div>
                                                        <div class="col-xs-12">
                                                            <div class=" del_spqt_top pull-right">
                                                                <a href="">Xóa</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>

                                    </div>
                                </div>
                            </li>
                            <li class="hidden-xs">
                                <a href="">đăng nhập</a>
                            </li>
                            <li class="hidden-xs">
                                <a href="">đăng ký</a>
                            </li>
                            <li class="cart_shop">
                                <a href="">Cart <i class="fa fa-shopping-cart" style="padding-left: 10px"></i>(0)</a>
                            </li>
                        </ul>
                        <ul class="list_link_top">
                            <li>
                                <a href="" class="fa fa-facebook-f"></a>
                            </li>
                            <li>
                                <a href="" class="fa fa-twitter"></a>
                            </li>
                            <li>
                                <a href=""  class="fa fa-pinterest"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="sticky-header">
        <div class="clearfix"></div>
        <div class="bg_menu">
            <div class="container">
                <div class="row_pc">

                    <div class="row">
                        <h1 class="hidden" style="margin: 0px; padding: 0">NỮ HOÀNG QUẦN JEAN</h1>
                        <div class="col-md-3 hidden-xs hidden-sm">
                            <div class="header_logo">
                                <a href="">
                                    <img class="w_100" src="img/logo.png" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-9 col-sm-12 col-xs-12">
                            <div class="pull-right w_100 top_main">
                                <div class="menu_main">
                                    <nav class="nav is-fixed" role="navigation" style="position: relative;z-index: 5;">
                                        <div class="wrapper wrapper-flush">
                                            <div class="nav-container">
                                                <div class="visible-xs">
                                                    <ul class="log_xs">
                                                        <li>
                                                            <a href="">
                                                                Đăng ký
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="">
                                                                Đăng nhập
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                                <ul class="nav-menu menu">
                                                    <li class="menu-item"> <a href="" class="menu-link">Trang chủ</a> </li>
                                                    <li class="menu-item"> <a href="" class="menu-link">Giới thiệu</a> </li>
                                                    <li class="menu-item has-dropdown">
                                                        <a href="" class="menu-link ">THÔNG BÁO</a>
                                                        <ul class="nav-dropdown menu">
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 1</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 2</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 3</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 4</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 5</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 6</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 7</a></li>
                                                            <li class="menu-item"> <a href="#" class="menu-link">THÔNG BÁO 8</a></li>
                                                        </ul>
                                                    </li>
                                                    <li class="menu-item"> <a href="" class="menu-link">THANH TOÁN & MUA HÀNG</a> </li>
                                                    <li class="menu-item"> <a href="" class="menu-link"> KHUYẾN MÃI</a> </li>
                                                    <li class="menu-item"> <a href="" class="menu-link">GÓP Ý</a> </li>
                                                    <li class="menu-item"> <a href="" class="menu-link">HỢP TÁC</a> </li>
                                                    <li class="menu-item"> <a href="" class="menu-link">Liên hệ</a> </li>

                                                </ul>
                                            </div>
                                        </div>
                                    </nav>
                                </div>
                                <div class="search_box">
                                    <div id="sb-search" class="sb-search">
                                        <form>
                                            <input class="sb-search-input" placeholder="Enter your search term..." type="text" value="" name="search" id="search">
                                            <input class="sb-search-submit" type="submit" value="">
                                            <span class="sb-icon-search"></span>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="bg_prod_cate_top clearfix">
            <div class="container">
                <div class="row_pc">
                    <ul class="prod_cate_top">
                        <li>
                            <a href="">
                                <img style="width: 28px; height: 28px" src="img/icon_jeans.png" alt=""/>
                                <span>Quần Bò</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img style="width: 28px; height: 28px" src="img/icon_dresses.png" alt=""/>
                                <span>Quần Bò</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img style="width: 28px; height: 28px" src="img/icon_baby_clothes.png" alt=""/>
                                <span>Quần Bò</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="slider_full">

        <div id="slider1_container" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1350px; height: 492px; overflow: hidden;">
            <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1350px;  height: 492px; overflow: hidden;">
                <div class="w_100 h_100">
                    <a href="" class="w_100 h_100"><img class="w_100 h_100" u="image" src="img/slider1.png" /></a>
                </div>
                <div class="w_100 h_100">
                    <a href="" class="w_100 h_100"><img class="w_100 h_100" u="image" src="img/slider2.png" /></a>
                </div>
            </div>
            <div u="navigator" class="jssorb21" style="position: absolute; bottom: 26px; left: 6px;">
                <div u="prototype" style="POSITION: absolute; WIDTH: 19px; HEIGHT: 19px; text-align:center; line-height:19px; color:White; font-size:12px;"></div>
            </div>
            <span u="arrowleft" class="jssora21l" style="width: 55px; height: 55px; top: 10px; left: 0px;">

            </span>
            <span u="arrowright" class="jssora21r" style="width: 55px; height: 55px; top: 100px; right: 0px;">

            </span>
        </div>
    </div>

</header>
<article>
    <div class="container">
        <div class="row_pc">

            <div class="tit_home">
                <a href="">
                    <img style="width: 28px; height: 28px" src="img/icon_jeans.png" alt=""/>
                    <span class="txt_tit_home">Quần Bò</span>
                </a>
            </div>
            <div class="clearfix"></div>
            <div class="list_prod_home">
                <div class="row">

                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="tit_home">
                <a href="">
                    <img style="width: 28px; height: 28px" src="img/icon_dresses.png" alt=""/>
                    <span class="txt_tit_home">Váy & Áo</span>
                </a>
            </div>
            <div class="clearfix"></div>
            <div class="list_prod_home">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="tit_home">
                <a href="">
                    <img style="width: 28px; height: 28px" src="img/icon_baby_clothes.png" alt=""/>
                    <span class="txt_tit_home">Quần áo trẻ em</span>
                </a>
            </div>
            <div class="clearfix"></div>
            <div class="list_prod_home">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                        <div class="box_prod_home">
                            <div class="img_prod_home">
                                <a class="h_15" href="">
                                    <img class="w_100" src="img/prod1.png" alt=""/>
                                </a>
                                <div class="view_prod_detail" style="display: none">
                                    Thông tin sản phẩm  Thông tin sản phẩm  Thông tin sản phẩm
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sub_prod_home">
                                <div class="name_prod_home"><a href="">Quần Jean Levi’s</a></div>
                                <div class="clearfix"></div>
                                <div class="prince_retail clearfix">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <div class="prince_new_retail">Giá lẻ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">860.000đ</span></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <div class="row">
                                            <del class="prince_old_retail pull-right">990.000đ</del>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="prince_wholesale_retail">Giá sỉ: <span style="font-size: 14px; color: #ff0000; font-weight: bold">680.000đ</span></div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="row">
                                        <div class="pull-right">
                                            <a class="fa fa-shopping-cart cart_pro_home"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</article>

<div class="clearfix"></div>

<footer class="footer">

    <div class="container">
        <div class="row_pc">
            <div class="row">
                <div class="col-xs-12 visible-xs">
                    <div class="" style="text-align: center;margin-top: 15px; color: #000">ĐĂNG KÝ KHUYẾN MẠI</div>
                    <div class="quote-form visible-xs" style="margin-top: 5px">
                        <form class="validate" action="" method="post">
                            <div class="input-group">
                                <input type="text" name="email" class="validate[required,custom[email]]  form-control" placeholder="Enter your email address..." id="form-validation-field-0">
                                  <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="fa fa-envelope" aria-hidden="true"></i>
                                        SUBSCRIBE
                                    </button>
                                  </span>
                            </div><!-- /input-group -->
                        </form>
                    </div>
                </div>

                <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                    <div class="tit_footer">Địa chỉ liên hệ</div>
                    <div class="clearfix"></div>
                    <div class="contact_footer">
                        <div class="" style="margin-bottom: 5px;font-size: 14px; font-weight: bold; text-transform: uppercase">
                            Nữ hoàng quần jeans
                        </div>
                        </p>
                        Địa chỉ: 33B, phố Phan Văn Trường, Cầu Giấy, Hà Nội
                        Số điện thoại: 01672255278
                    </div>
                </div>
                <div class="col-md-6 col-sm-4 col-xs-6 col-480-12">
                    <div class="tit_footer">Fan Page</div>
                    <div class="clearfix"></div>

                    <div class="fb-page" style="max-width: 100%; overflow: hidden" data-href="https://www.facebook.com/facebook" data-tabs="timeline"
                         data-width="325" data-height="205" data-small-header="false"
                         data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                        <div class="fb-xfbml-parse-ignore">
                            <blockquote cite="https://www.facebook.com/facebook"><a
                                    href="https://www.facebook.com/facebook">Facebook</a></blockquote>
                        </div>
                    </div>

                </div>
                <div class="col-md-3 col-sm-4 col-xs-6 col-480-12">
                    <div class="tit_footer">thông tin thanh toán</div>
                    <div class="clearfix"></div>
                    <div class="contact_footer" style="color: #0a0a0a; line-height: 25px">
                        Ngân hàng BIDV
                        </p>
                        Chủ tài khoản: Nguyễn Quốc Cường
                        </p>
                        Số tài khoản: 1234567898766
                    </div>
                    <div class="clearfix"></div>
                    <ul class="list_bank_footer pull-right">
                        <li>
                            <a href="">
                                <img style="width: 50px; height: 30px" src="img/bank1.png" alt=""/>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img style="width: 50px; height: 30px" src="img/bank2.png" alt=""/>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img style="width: 50px; height: 30px" src="img/bank3.png" alt=""/>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img style="width: 50px; height: 30px" src="img/bank4.png" alt=""/>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="js/classie.js"></script><!-- search -->
    <script type="text/javascript" src="js/uisearch.js"></script><!-- search -->
    <script>
        new UISearch( document.getElementById( 'sb-search' ) );
    </script><!-- search -->
    <script type="text/javascript">
        if (window.innerWidth > 320) {
            $(window).scroll(function () {
                if ($(window).scrollTop() >= 36) {
                    $('.sticky-header').addClass('fixed');
                }
                else {
                    $('.sticky-header').removeClass('fixed');
                }
            });
        }

        if (window.innerWidth > 320) {
            $(window).scroll(function () {
                if ($(window).scrollTop() >= 36) {
                    $('.sticky-header').addClass('fixed');
                }
                else {
                    $('.sticky-header').removeClass('fixed');
                }
            });
        }

        /* When the user clicks on the button,
         toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('.dropbtn')) {

                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
</footer>

</body>
</html>
