<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Zend</title>
            <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.min.css')  ?>
         <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css')  ?>
         <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-3.1.1.min.js')  ?>
         <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js')  ?>
    </head>
    <body>
    <?php echo $this->render('/header.phtml') ?>
    <content>
      <?php echo $this->render('/content.phtml') ?>
    </content>
    <!-- //<?php echo $this->render('/footer.phtml') ?>-->
</body>
</html>
