<div class="row">
    <div class="col-sm-12">
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="http://thoitrangfshop.com/vnadmin">Dashboard</a>
            </li>
            <li class="active">
                <a href="http://thoitrangfshop.com/vnadmin/product/products">Danh sách Sản phẩm(<span class="name_lang"> Tiếng Việt</span>)</a>
            </li>
            <li class="active">
                <a href="http://thoitrangfshop.com/vnadmin/product/categories">Danh mục</a>
            </li>
            <li>
                <a onclick="history.back()" style="cursor: pointer"><i class="fa fa-reply"></i></a>
            </li>
            <li class="pull-right images_lang">
                <img src="http://thoitrangfshop.com/img/vn.jpg" alt="Images Language" style="max-width: 30px"> </li>                                    </ol>
    </div>
    <div class="col-md-12">

        <div class="body collapse in" id="div1">
            <form class="form-horizontal" role="form" id="form1" method="POST" <?php echo 'action="' . $this->url(array('controller' => 'Category', 'action' => 'add', 'module' => "product")) . '"' ?>  enctype="multipart/form-data">
                <input type="hidden" name="edit" value="">
                <input type="hidden" name="lang" value="1">
                <div class="col-md-8" style="font-size: 12px">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title pull-left">Tổng quan</h3>
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-xs" name="addcate"><i class="fa fa-check"></i> Thêm                                        </button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">

                            <div class="form-group">
                                <label class="col-sm-12">
                                    Tên danh mục  (<span class="name_lang"> Tiếng Việt</span>)   :
                                </label>
                                <div class="col-sm-12">
                                    <input type="text" class="validate[required] form-control input-sm " name="name" value="" placeholder="">
                                    <input type="hidden" class="form-control input-sm " name="is_cate" value="1" placeholder="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">
                                    Alias
                                </label>
                                <div class="col-sm-12">
                                    <input type="text" class="form-control input-sm " name="alias" value="" placeholder="">
                                </div>
                            </div>
                            <div class="form-group" style="display: none">
                                <label class="col-sm-12">
                                    Tên mô tả tiếng anh   :
                                </label>
                                <div class="col-sm-12">
                                    <input type="text" class="form-control input-sm " name="name_alias" value="" placeholder="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">Danh mục cha:</label>
                                <div class="col-sm-12">
                                    <select name="parent" class="form-control input-sm">
                                        <option value="0">Lựa chọn</option>
                                        <?php

                                        function viewMenu($arrayMenu) {
                                            for ($i = 0; $i < sizeof($arrayMenu); $i++) {
                                                echo '<option value=' . $arrayMenu[$i]->getDataId() . '">' . $arrayMenu[$i]->getCurrentMenu() . '</option>';
                                                $_COUNT = 0;
                                                loopChildMenu($arrayMenu[$i], $_COUNT);
                                            }
                                        }

                                        function loopChildMenu($menu, $_COUNT) {
                                            // $_COUNT use to reset index root menu
                                            STATIC $_count = 0;
                                            if ($_COUNT == 0) {
                                                $_count = $_COUNT;
                                            }
                                            if (sizeof($menu->getArrayChildMenu()) > 0) {
                                                for ($i1 = 0; $i1 < sizeof($menu->getArrayChildMenu()); $i1 ++) {
                                                    echo '<option value=' . $menu->getArrayChildMenu()[$i1]->getDataId() . '">' . expression($_count) . '-' . $menu->getArrayChildMenu()[$i1]->getCurrentMenu() . '</option>';
                                                    loopChildMenu($menu->getArrayChildMenu()[$i1], ++$_count);
                                                }
                                            } else {
                                                --$_count;
                                            }
                                        }

                                        /**
                                         * print '-' follow menu
                                         * @param type $_count
                                         * @return string
                                         */
                                        function expression($_count) {
                                            $express = '';
                                            for ($i = 0; $i < $_count; $i++) {
                                                $express .= ' - ';
                                            }
                                            return $express;
                                        }

                                        viewMenu($this->listCategory);
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12 ">Thứ tự:</label>
                                <div class="col-lg-2">
                                    <input type="number" name="sort" class="form-control input-sm" value="8">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12  ">Nội dung:</label>
                                <div class="col-lg-12">
                                    <textarea name="description" id="ckeditor" class="form-control input-sm" placeholder="Mô tả" rows="7" style="visibility: hidden; display: none;"></textarea>
                                    <script type="text/javascript" src="http://nhamaygda.com/assets/ckeditor/ckeditor.js"></script><script type="text/javascript">CKEDITOR_BASEPATH = 'http://nhamaygda.com/assets/ckeditor/';</script>
                                    <script type="text/javascript">
                                        CKEDITOR.replace('ckeditor', {toolbar: 'Full', width: '100%', height: '300px'});</script>                                        </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">SEO title:</label>
                                <div class="col-sm-12">
                                    <input type="text" name="title_seo" class="input-sm form-control" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">SEO keyword:</label>
                                <div class="col-sm-12">
                                    <textarea name="keyword_seo" class="form-control input-sm" placeholder=""></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">SEO description:</label>
                                <div class="col-sm-12">
                                    <textarea name="description_seo" class="form-control input-sm" placeholder="" rows="4"></textarea>
                                </div>
                            </div>

                            <div class=" ">
                                <button type="submit" class="btn btn-success btn-xs pull-right" name="addcate">
                                    <i class="fa fa-check"></i> Thêm</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3" style="font-size: 12px">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title pull-left">Tùy chọn</h3>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">

                            <div class="form-group">
                                <label class="col-sm-12">Thứ tự:</label>
                                <div class="col-sm-12">
                                    <input type="number" name="sort" class="form-control input-sm" value="5">
                                </div>
                            </div>
                            <div class="form-group" style="display: none">
                                <label for="inputEmail1" class="col-sm-12">Màu:</label>
                                <div class="col-sm-1 ">
                                    <div class="btn btn-sm btn-default"><i class="fa fa-check"></i></div>
                                </div>
                                <div class="col-sm-10 color1" id="color_input">
                                    <div class="minicolors minicolors-theme-bootstrap minicolors-position-bottom minicolors-position-left"><input name="color" type="text" id="hue-demo" class="form-control color_picker minicolors-input input-sm" data-control="hue" value="" size="7"><span class="minicolors-swatch minicolors-sprite"><span class="minicolors-swatch-color"></span></span><div class="minicolors-panel minicolors-slider-hue"><div class="minicolors-slider minicolors-sprite"><div class="minicolors-picker" style="top: 0px;"></div></div><div class="minicolors-opacity-slider minicolors-sprite"><div class="minicolors-picker"></div></div><div class="minicolors-grid minicolors-sprite" style="background-color: rgb(255, 0, 0);"><div class="minicolors-grid-inner"></div><div class="minicolors-picker" style="top: 150px; left: 0px;"><div></div></div></div></div></div>

                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">Hiển thị:</label>

                                <div class="col-sm-12">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="1" name="home">
                                        Tab danh mục                                            </label>
                                    &nbsp;&nbsp;&nbsp;
                                    <div class="clearfix "></div>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="1" name="focus">
                                        Hiển thị sản phẩm ra trang chủ                                            </label>
                                    <div class="clearfix hidden"></div>
                                    <label class="hidden">
                                        <input type="checkbox " value="1" name="hot">
                                        Hiển thị trang chủ (sim)                                            </label>
                                </div>
                            </div>
                            <div class="form-group display_none">
                                <label class="col-sm-12">Icon:</label>
                                <div class="col-lg-12">
                                    <input type="hidden" name="icon" id="caticon" value="">
                                    <div style="float: left;position: relative; display:none">
                                        <div id="showcaticon" style="border: 1px #ddd dotted;padding: 10px;float: left">
                                        </div>
                                        <div id="icon_option" style="position: absolute;top:5px;right:5px">
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="btn btn-xs btn-default pull-left" data-item="#caticon" data-toggle="modal" data-target="#exampleModal">
                                        Chọn icon</div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">Ảnh : (370 * 455)</label>
                                <div class="col-sm-12">
                                    <input type="file" name="userfile" id="input_img" onchange="handleFiles()">

                                    <div>
                                        <img src="" id="image_review">                                            </div>
                                </div>
                            </div>


                            <div class="form-group " style="display: none">
                                <label class="col-sm-12">Logo trang danh mục:</label>
                                <div class="col-sm-12">
                                    <input type="file" name="userfile2" id="input_img2" onchange="handleFiles2()">

                                    <div>
                                        <img src="" id="image_review2">                                            </div>
                                </div>
                            </div>

                            <div class="form-group " style="display: none">
                                <label class="col-sm-12">Ảnh nền trang danh mục:</label>
                                <div class="col-sm-12">
                                    <input type="file" name="userfile3" id="input_img2" onchange="handleFiles2()">

                                    <div>
                                        <img src="" id="image_review2">                                            </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>



            </form>
        </div>
    </div>
</div>