<script>
    $(document).ready(function ()
    {
        var updateOutput = function (e)
        {
            var list = e.length ? e : $(e.target),
                    output = list.data('output');
            if (window.JSON) {
                output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
            } else {
                output.val('JSON browser support required for this demo.');
            }
        };

        // activate Nestable for list 1
        $('#nestable').nestable({
            group: 1
        })
                .on('change', updateOutput);

        // output initial serialised data
        updateOutput($('#nestable').data('output', $('#nestable-output')));

        $('#nestable-menu').on('click', function (e)
        {
            var target = $(e.target),
                    action = target.data('action');
            if (action === 'expand-all') {
                $('.dd').nestable('expandAll');
            }
            if (action === 'collapse-all') {
                $('.dd').nestable('collapseAll');
            }
        });
    });
</script> 
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="http://thoitrangfshop.com/vnadmin">Admin</a>
            </li>
            <li class="active">
                <a href="http://thoitrangfshop.com/vnadmin/product/products">Danh sách Sản phẩm  (<span class="name_lang"> Tiếng Việt</span>)</a>
            </li>
            <li class="active">
                <a href="http://thoitrangfshop.com/vnadmin/product/categories">
                    Danh mục                        </a>
            </li>
            <li class="pull-right images_lang">
                <img src="http://thoitrangfshop.com/img/vn.jpg" alt="Images Language" style="max-width: 30px"> </li>                </ol>
    </div>

</div>
<div class="row">
    <div class="col-sm-2" >
        <?php echo '<form action="' . $this->url(array('controller' => 'Category', 'action' => 'add', 'module' => "product")) . '" method="get">' ?>
        <button class="btn btn-primary" name="Thêm" value="Thêm" id="btnAddMenu">Thêm Danh mục</button>

        </form>

    </div>
    <div class="col-lg-2">
        <?php echo '<form action="' . $this->url(array('controller' => 'Category', 'action' => 'save', 'module' => "product")) . '" method="post">' ?>
        <button class="btn btn-primary" name ="Thêm" value="Thêm" id="btnSaveMenu">Lưu danh mục</button>
        <input type="hidden" value="nestable-output" id="nestable-output" name="newcategory"/>   
        <input type="hidden"  name="menuPosition" <?php echo 'value="' . $this->menuPosition . '"' ?> />   
        </form>
    </div>

</div>
<div class="row top_space">
    <div class="cf nestable-lists">
        <div class="dd" id="nestable">
            <ol class="dd-list">
                <?php

                function viewMenu($arrayMenu, $controller) {
                    for ($i = 0; $i < sizeof($arrayMenu); $i++) {
                        loopChildMenu($arrayMenu[$i], $controller);
                    }
                }

                function loopChildMenu($menu, $controller) {
                    echo '<li class="dd-item dd3-item"  data-id="' . $menu->getDataId() . '"  >';
                    echo '<div class="dd-handle dd3-handle">Drag</div>';
                    echo '<div class="dd3-content" onclick="location.href=\'' . $controller . '/id/' . $menu->getDataId() . '\'">' . $menu->getCurrentCategory() . '</div>';
                    if (sizeof($menu->getArrayChildCategory()) > 0) {
                        echo ' <ol class="dd-list">';
                        for ($i1 = 0; $i1 < sizeof($menu->getArrayChildCategory()); $i1 ++) {
                            loopChildMenu($menu->getArrayChildCategory()[$i1], $controller);
                        }
                        echo '</ol>';
                    }
                    echo '</li>';
                }

                viewMenu($this->listCategory, $this->url(array('controller' => 'Category', 'action' => 'edit', 'module' => "product"), null, true));
                ?>
            </ol>
        </div>
    </div>
</div>