<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="http://thoitrangfshop.com/vnadmin">Admin</a>
            </li>
            <li class="active">
                <a href="http://thoitrangfshop.com/vnadmin/product/products">Danh sách Sản phẩm  (<span class="name_lang"> Tiếng Việt</span>)</a>
            </li>
            <li class="active">
                <a href="http://thoitrangfshop.com/vnadmin/product/categories">
                    Danh mục                        </a>
            </li>
            <li class="pull-right images_lang">
                <img src="http://thoitrangfshop.com/img/vn.jpg" alt="Images Language" style="max-width: 30px"> </li>                </ol>
    </div>
    <div class="col-md-12">

        <div class="" style="padding-bottom: 15px">
            <a <?php echo 'href="' . $this->url(array('controller' => 'Category', 'action' => 'add', 'module' => "product")) . '"'; ?> class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i> Thêm
            </a>
        </div>

        <div class=" ">
            <table class="table table-striped table-bordered">
                <tbody><tr>
                        <th width="7%">Sắp xếp</th>
                        <th>Tên</th>
                        <th width="20%">Ảnh</th>
                        <th class="hidden" width="6%">Màu Nền</th>
                        <th class="" width="8%">Hiển thị</th>
                        <th width="8%" class="text-center">Action</th>
                    </tr>

                    <tr>
                        <td>
                            <input type="number" value="1" data-item="25" onchange="cat_sort($(this))" style="width: 45px; padding: 2px;border:1px solid #ddd">
                        </td>
                        <td>Quần Jean</td>
                        <td><img src="http://thoitrangfshop.com/upload/img/ada0b05df6b78db9a1da5067cf3ce05e.png" style="height:40px; max-width:100px"> </td>

                        <td class="text-center">
                            <div data-toggle="tooltip" data-placement="top" title="" data-value="25" data-view="home" class="view_color" style="border: 1px solid #000088;margin-right: 10px; background:#000088" data-original-title="Tab danh mục"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="25" data-view="focus" class="view_color" style="border: 1px solid #008855;margin-right: 10px;background:#008855 " data-original-title="Hiển thị sản phẩm ra trang chủ"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="25" data-view="hot" class="view_color hidden" style="border: 1px solid #EE1700;margin-right: 10px;background:#EE1700 " data-original-title="Hiển thị trang chủ (sim)"></div>

                        </td>


                        <td class="text-center">
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_edit/25?is_cat=1" class="btn btn-xs btn-default" title="Sửa"><i class="fa fa-pencil"></i></a>
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_delete/25" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-xs btn-danger" title="Xóa" style="color: #fff"><i class="fa fa-times"></i> </a>
                        </td>
                    </tr><tr>
                        <td>
                            <input type="number" value="2" data-item="26" onchange="cat_sort($(this))" style="width: 45px; padding: 2px;border:1px solid #ddd">
                        </td>
                        <td>Váy &amp; Áo</td>
                        <td><img src="http://thoitrangfshop.com/upload/img/31aa8e4ccf05c88bbaf9f081f79b60b9.png" style="height:40px; max-width:100px"> </td>

                        <td class="text-center">
                            <div data-toggle="tooltip" data-placement="top" title="" data-value="26" data-view="home" class="view_color" style="border: 1px solid #000088;margin-right: 10px; background:#000088" data-original-title="Tab danh mục"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="26" data-view="focus" class="view_color" style="border: 1px solid #008855;margin-right: 10px;background:#008855 " data-original-title="Hiển thị sản phẩm ra trang chủ"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="26" data-view="hot" class="view_color hidden" style="border: 1px solid #EE1700;margin-right: 10px;background:#EE1700 " data-original-title="Hiển thị trang chủ (sim)"></div>

                        </td>


                        <td class="text-center">
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_edit/26?is_cat=1" class="btn btn-xs btn-default" title="Sửa"><i class="fa fa-pencil"></i></a>
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_delete/26" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-xs btn-danger" title="Xóa" style="color: #fff"><i class="fa fa-times"></i> </a>
                        </td>
                    </tr><tr>
                        <td>
                            <input type="number" value="3" data-item="1" onchange="cat_sort($(this))" style="width: 45px; padding: 2px;border:1px solid #ddd">
                        </td>
                        <td>Quần áo trẻ em</td>
                        <td><img src="http://thoitrangfshop.com/upload/img/a213afb75197f3ee60064bb3934e4ead.png" style="height:40px; max-width:100px"> </td>

                        <td class="text-center">
                            <div data-toggle="tooltip" data-placement="top" title="" data-value="1" data-view="home" class="view_color" style="border: 1px solid #000088;margin-right: 10px; background:#000088" data-original-title="Tab danh mục"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="1" data-view="focus" class="view_color" style="border: 1px solid #008855;margin-right: 10px;background:#008855 " data-original-title="Hiển thị sản phẩm ra trang chủ"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="1" data-view="hot" class="view_color hidden" style="border: 1px solid #EE1700;margin-right: 10px;background:#EE1700 " data-original-title="Hiển thị trang chủ (sim)"></div>

                        </td>


                        <td class="text-center">
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_edit/1?is_cat=1" class="btn btn-xs btn-default" title="Sửa"><i class="fa fa-pencil"></i></a>
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_delete/1" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-xs btn-danger" title="Xóa" style="color: #fff"><i class="fa fa-times"></i> </a>
                        </td>
                    </tr><tr>
                        <td>
                            <input type="number" value="4" data-item="2" onchange="cat_sort($(this))" style="width: 45px; padding: 2px;border:1px solid #ddd">
                        </td>
                        <td>Áo sơ mi</td>
                        <td><img src="http://thoitrangfshop.com/upload/img/454bc01d37334cf1757bf3e884ac2d8e.png" style="height:40px; max-width:100px"> </td>

                        <td class="text-center">
                            <div data-toggle="tooltip" data-placement="top" title="" data-value="2" data-view="home" class="view_color" style="border: 1px solid #000088;margin-right: 10px; background:#000088" data-original-title="Tab danh mục"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="2" data-view="focus" class="view_color" style="border: 1px solid #008855;margin-right: 10px; " data-original-title="Hiển thị sản phẩm ra trang chủ"></div>

                            <div data-toggle="tooltip" data-placement="top" title="" data-value="2" data-view="hot" class="view_color hidden" style="border: 1px solid #EE1700;margin-right: 10px;background:#EE1700 " data-original-title="Hiển thị trang chủ (sim)"></div>

                        </td>


                        <td class="text-center">
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_edit/2?is_cat=1" class="btn btn-xs btn-default" title="Sửa"><i class="fa fa-pencil"></i></a>
                            <a href="http://thoitrangfshop.com/vnadmin/product/cat_delete/2" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-xs btn-danger" title="Xóa" style="color: #fff"><i class="fa fa-times"></i> </a>
                        </td>
                    </tr>                                            </tbody></table>
        </div>
    </div>
</div>