<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> <a href="#">Dashboard</a>
            </li>
        </ol>
    </div>
</div>
<!--<div class="row">
    <div class="col-lg-12">
        <button class="btn btn-primary" name="Thêm" value="Thêm" id="btnAddMenu">Thêm Menu</button>
        <button class="btn btn-primary" name="Thêm" value="Thêm" id="btnSaveMenu">Lưu vị trí</button>
    </div>
</div>-->
<div class="row top_space" >

    <form action="" method="post">
        <label for="ahihi">Name</label><input type="text" name="name" value="" /> 
        <label for="ahihi">Alias</label><input type="text" name="Alias" value="" /> 
        <label for="ahihi">Parent Menu</label><input type="text" name="name" value="" /> 
        <label for="ahihi">Module</label><input type="text" name="name" value="" /> 
        <label for="ahihi">Position</label><input type="text" name="name" value="" /> 
        <label for="ahihi">Content</label><input type="text" name="name" value="" /> 
    </form>

</div>

