<div class="row">
    <div class="col-sm-12">
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="http://nhamaygda.com/vnadmin">Dashboard</a>
            </li>
            <li>
                <a href="http://nhamaygda.com/vnadmin/menu/menulist">Menus</a>
            </li>
        </ol>
    </div>
    <div class="col-md-12">
        <div class="body collapse in" id="div1">
            <form class="form-horizontal" role="form" id="form1" method="POST" <?php echo 'action="' . $this->url(array('controller' => 'Home', 'action' => 'edit', 'module' => "menu", "menuPosition" => "top")) . '"' ?> enctype="multipart/form-data">
                <input type="hidden" name="edit_id" value="">
                <input type="hidden" value="vi" id="lang">
                <div class="col-md-8" style="font-size: 12px">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title pull-left">Tổng quan</h3>

                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-sm" name="deleteMenu"><i class="fa fa-delete"></i> Xóa
                                </button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body" style="min-height: 530px">
                            <div class="form-group">
                                <label for="inputEmail1" class="col-sm-2 control-label">Tên menu:</label>

                                <div class="col-sm-7">
                                    <input type="text" class="form-control input-sm " name="title" <?php echo 'value="' . $this->currentMenu['name'] . '"' ?>  placeholder="Tên menu">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Alias:</label>
                                <div class="col-sm-7">
                                    <input type="text" class="form-control input-sm " name="alias" <?php echo 'value="' . $this->currentMenu['alias'] . '"' ?> placeholder="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Vị trí:</label>

                                <div class="col-sm-5">
                                    <select name="position" class="form-control input-sm" onchange="select_lang($('#lang').val(), $(this).val())" id="position">
                                        <option value="top" <?php
                                        if ($this->currentMenu['position'] == 'top') {
                                            echo 'selected=""';
                                        }
                                        ?>>Menu top</option>
                                        <option value="left" <?php
                                        if ($this->currentMenu['position'] == 'left') {
                                            echo 'selected=""';
                                        }
                                        ?>>Menu left</option>
                                        <option value="right" <?php
                                        if ($this->currentMenu['position'] == 'right') {
                                            echo 'selected=""';
                                        }
                                        ?>>Menu right</option>
                                        <option value="bottom" <?php
                                        if ($this->currentMenu['position'] == 'bottom') {
                                            echo 'selected=""';
                                        }
                                        ?>>Menu bottom</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail1" class="col-sm-2 control-label">Menu cha:</label>

                                <div class="col-sm-5">
                                    <select name="parent" class="form-control input-sm" id="parent_menu">

                                        <?php

                                        function viewMenu($arrayMenu, $parentMenu) {
                                            for ($i = 0; $i < sizeof($arrayMenu); $i++) {
                                                echo '<option ';
                                                if ($parentMenu === $arrayMenu[$i]->getDataId()) {
                                                    echo 'selected=""';
                                                }
                                                echo 'value="' . $arrayMenu[$i]->getDataId();
                                                echo '">' . $arrayMenu[$i]->getCurrentMenu() . '</option>';
                                                $_COUNT = 0;
                                                loopChildMenu($arrayMenu[$i], $_COUNT, $parentMenu);
                                            }
                                        }

                                        function loopChildMenu($menu, $_COUNT, $parentMenu) {
                                            // $_COUNT use to reset index root menu
                                            STATIC $_count = 0;
                                            if ($_COUNT == 0) {
                                                $_count = $_COUNT;
                                            }
                                            if (sizeof($menu->getArrayChildMenu()) > 0) {
                                                for ($i1 = 0; $i1 < sizeof($menu->getArrayChildMenu()); $i1 ++) {
                                                    echo '<option ';
                                                    if ($parentMenu === $menu->getArrayChildMenu()[$i1]->getDataId()) {
                                                        echo 'selected=""';
                                                    }
                                                    echo 'value="' . $menu->getArrayChildMenu()[$i1]->getDataId() . '">' . expression($_count) . '-' . $menu->getArrayChildMenu()[$i1]->getCurrentMenu() . '</option>';
                                                    loopChildMenu($menu->getArrayChildMenu()[$i1], ++$_count, $parentMenu);
                                                }
                                            } else {
                                                --$_count;
                                            }
                                        }

                                        /**
                                         * print '-' follow menu
                                         * @param type $_count
                                         * @return string
                                         */
                                        function expression($_count) {
                                            $express = '';
                                            for ($i = 0; $i < $_count; $i++) {
                                                $express .= ' - ';
                                            }
                                            return $express;
                                        }

                                        viewMenu($this->listMenu, $this->currentMenu['root_menu']);
                                        ?>
                                        <option value="-1">None</option>   
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Module:</label>

                                <div class="col-sm-5">
                                    <!--<option value="news" /**/ >Tin tức</option>-->
                                    <select name="module" id="sc_get" class="form-control input-sm">
                                        <?php
                                        foreach ($this->listModules as $module) {
                                            echo '<option ';
                                            if ((int) $module['id'] === $this->currentMenu['module']) {
                                                echo 'selected=""';
                                            }
                                            echo 'value="' . $module['id'] . '">' . $module['name'] . '</option>';
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Trỏ đến:</label>

                                <div class="col-sm-5">
                                    <select name="subcat" id="sc_show" class="form-control input-sm"><option value="tin-tuc-su-kien">Tin tức - Sự kiện</option><option value="video">Video</option></select>
                                </div>
                            </div>
                            <!--                            <div class="form-group">
                                                            <label class="col-sm-2 control-label">URL:</label>
                            
                                                            <div class="col-md-9">
                                                                <input name="url" type="text" id="url_menu" class="form-control input-sm" value="">
                            
                                                                <input type="hidden" id="products" value="danh-muc">
                                                                <input type="hidden" id="types" value="tour-types">
                                                                <input type="hidden" id="news" value="tin-tuc">
                                                                <input type="hidden" id="pages" value="page">
                                                                <input type="hidden" id="styles" value="travel-style">
                                                                                    <input type="hidden" id="posts" value="">
                            
                                                            </div>
                                                        </div>-->

                            <div class="form-group">
                                <label for="inputEmail1" class="col-sm-2 control-label">Mô Tả:</label>

                                <div class="col-sm-9">
                                    <textarea name="description" rows="6" class="form-control input-sm" placeholder="Mô tả"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail1" class="col-sm-2 control-label "> </label>

                                <div class="col-sm-5">
                                    <div class="text-right">
                                        <input type="hidden" <?php echo 'value="' . $this->currentMenu['id'] . '"' ?> name="id" />
                                        <button type="submit" class="btn btn-success btn-sm" name="editMenu"><i class="fa fa-save"></i> Lưu
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!---endleft--->
                <!--                <div class="col-md-4" style="font-size: 12px;padding:0px">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">Tùy chọn</h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label">Target:</label>
                
                                                <div class="col-md-5">
                
                                                    <label class="radio-inline">
                                                        <input type="radio" name="target" value="" checked="">Tab hiện tại
                                                    </label>
                                                    <label class="radio-inline">
                                                        <input type="radio" name="target" value="_blank"> Tab mới
                                                    </label>
                                                </div>
                                            </div>
                                            <input type="hidden" id="baseurl" value="http://nhamaygda.com/">
                
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label">Ảnh:</label>
                
                                                <div class="col-sm-3">
                                                    <input type="file" name="userfile" id="input_img" onchange="handleFiles()">
                
                
                                                    <img src="" id="image_review">                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->
            </form>
        </div>
    </div>

</div>