<script>
    $(document).ready(function ()
    {
        var updateOutput = function (e)
        {
            var list = e.length ? e : $(e.target),
                    output = list.data('output');
            if (window.JSON) {
                output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
            } else {
                output.val('JSON browser support required for this demo.');
            }
        };

        // activate Nestable for list 1
        $('#nestable').nestable({
            group: 1
        })
                .on('change', updateOutput);

        // output initial serialised data
        updateOutput($('#nestable').data('output', $('#nestable-output')));

        $('#nestable-menu').on('click', function (e)
        {
            var target = $(e.target),
                    action = target.data('action');
            if (action === 'expand-all') {
                $('.dd').nestable('expandAll');
            }
            if (action === 'collapse-all') {
                $('.dd').nestable('collapseAll');
            }
        });
    });
</script> 
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> <a href="#">Dashboard</a>
            </li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo '<form action="' . $this->url(array('controller' => 'Home', 'action' => 'save', 'module' => "menu", "menuPosition" => $this->menuPosition)) . '">' ?>
        <button class="btn btn-primary" name="Thêm" value="Thêm" id="btnAddMenu">Thêm Menu</button>
        <button class="btn btn-primary" name ="Thêm" value="Thêm" id="btnSaveMenu">Lưu vị trí</button>
        <input type="hidden" value="nestable-output" id="nestable-output" />   
        </form>
    </div>
</div>
<div class="row top_space">
    <div class="cf nestable-lists">
        <div class="dd" id="nestable">
            <ol class="dd-list">
                <?php

                function viewMenu($arrayMenu) {
                    for ($i = 0; $i < sizeof($arrayMenu); $i++) {
                        loopChildMenu($arrayMenu[$i]);
                    }
                }

                function loopChildMenu($menu) {
                    echo '<li class="dd-item"  data-id="' . $menu->getDataId() . '"  >';
                    echo '<div class="dd-handle">' . $menu->getCurrentMenu() . '</div>';
                    if (sizeof($menu->getArrayChildMenu()) > 0) {
                        echo ' <ol class="dd-list">';
                        for ($i1 = 0; $i1 < sizeof($menu->getArrayChildMenu()); $i1 ++) {
                            loopChildMenu($menu->getArrayChildMenu()[$i1]);
                        }
                        echo '</ol>';
                    }
                    echo '</li>';
                }

                viewMenu($this->listMenu);
                ?>
            </ol>
        </div>
    </div>
</div>